spring.application.name=api

server.port=8080

spring.datasource.url=jdbc:mariadb://localhost:3306/unifortrade
spring.datasource.username=unifortrade
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false

app.jwt.secret=change-this-dev-only-secret-change-this-dev-only-secret
app.jwt.access-token-expiration-minutes=60
app.jwt.refresh-token-expiration-days=30

app.cors.allowed-origins=http://localhost:3000

springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.persistAuthorization=true
